version: '2'

services:
  ethereum:
    build: .
    container_name: ethereum
    volumes:
    - ./hardhat.eth.ts:/usr/src/app/hardhat.config.ts
    ports:
    - "8545:8545"
  polygon:
    build: .
    env_file:
      - .env
    container_name: polygon
    volumes:
      - ./hardhat.polygon.ts:/usr/src/app/hardhat.config.ts
    ports:
      - "8546:8545"
  xdai:
    build: .
    container_name: xdai
    volumes:
      - ./hardhat.xdai.ts:/usr/src/app/hardhat.config.ts
    ports:
      - "8547:8545"
  fantom:
    build: .
    env_file:
      - .env
    container_name: fantom
    volumes:
      - ./hardhat.fantom.ts:/usr/src/app/hardhat.config.ts
    ports:
      - "8548:8545"
  avalanche:
    build: .
    env_file:
      - .env
    container_name: avalanche
    volumes:
      - ./hardhat.avalanche.ts:/usr/src/app/hardhat.config.ts
    ports:
      - "8549:8545"